Post: openQA and PowerPC
openQA-Bites/Blog pull request #4
Opened 2024-11-11 13:33 UTC by grisu48

Adds the blog post about openQA and PowerPC.

2024-11-11 15:06 UTC, okurz requested changes

2024-11-11 15:06 UTC, okurz commented on content/posts/2024/2024-11-11-openQA_and_PowerPC.md
> +Due to recent changes in the worker configuration, we needed to reconfigure some of the PowerPC jobs in openQA. This triggered a couple of questions regarding the availability of openQA worker, worke
You might want to clarify that actually no changes were done in upstream openQA. You are talking about a SUSE-internal infrastructure change only.

2024-11-11 15:25 UTC, grisu48 commented on content/posts/2024/2024-11-11-openQA_and_PowerPC.md
> +The internal hypervisor is backed directly into a PowerPC and is managed by the VIOS (virtual input output server). VIOS is AIX based IO hub system which runs as a separate essential VM on the PowerP
backed as in https://plainenglish.com/expressions/backed-by/, but I need to write it then as "backed by PowerPC directly". Thanks for the note!

2024-11-11 15:40 UTC, okurz approved these changes

2024-11-12 12:32 UTC, nicksinger commented
LGTM :+1:

2024-11-12 13:00 UTC, merged

2024-11-12 13:01 UTC, grisu48 commented
Thank you!